// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/api/game/start": {
            "post": {
                "description": "받은 명세서에 알맞게 게임 시작",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "게임 시작",
                "parameters": [
                    {
                        "description": "게임 명세",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.GameStartReq"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.GameInfo": {
            "type": "object",
            "properties": {
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.PlayerInfo"
                    }
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "main.GameStartReq": {
            "type": "object",
            "properties": {
                "game_info": {
                    "$ref": "#/definitions/main.GameInfo"
                },
                "map_info": {
                    "$ref": "#/definitions/main.MapInfo"
                },
                "timeout": {
                    "type": "integer"
                }
            }
        },
        "main.MapInfo": {
            "type": "object",
            "properties": {
                "floor": {
                    "type": "integer"
                },
                "horizontal": {
                    "type": "integer"
                },
                "locktime": {
                    "type": "integer"
                },
                "vertical": {
                    "type": "integer"
                }
            }
        },
        "main.PlayerInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "stat": {
                    "$ref": "#/definitions/main.Stat"
                }
            }
        },
        "main.Stat": {
            "type": "object",
            "properties": {
                "int": {
                    "type": "integer"
                },
                "pow": {
                    "type": "integer"
                },
                "spd": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
